[theme]
base = "dark"
primaryColor = "#4CAF50"         # Green for PlantUnify identity
backgroundColor = "#0E1117"      # Deep dark background
secondaryBackgroundColor = "#1E222A"
textColor = "#FFFFFF"
font = "sans serif"
